version: "3.7"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: gatsby develop --host 0.0.0.0
  text-to-speech:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./text-to-speech:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=My First Project-08241ca3f2bf.json
    command: node server.js